Repository hyperledger-labs/private-data-objects, pull requests merged in 2019-06, with the labels that each got.

#215 New Replcation and transaction Modules
  build/__tools__/run-tests.sh
  build/opt/pdo/etc/template/pcontract.toml
  client/pdo/client/controller/commands/create.py
  client/pdo/client/controller/commands/send.py
  client/pdo/client/scripts/AuctionTestCLI.py
  client/pdo/client/scripts/CreateCLI.py
  client/pdo/client/scripts/ShellCLI.py
  client/pdo/client/scripts/UpdateCLI.py
  python/pdo/contract/__init__.py
  python/pdo/contract/contract.py
  python/pdo/contract/replication.py
  python/pdo/contract/request.py
  python/pdo/contract/response.py
  python/pdo/contract/state.py
  python/pdo/contract/transaction.py
  python/pdo/service_client/__init__.py
  python/pdo/service_client/storage.py
  python/pdo/test/contract.py
  python/pdo/test/request.py
Labels: enhancement

#220 Change service shutdown to use signals #165
  eservice/Makefile
  eservice/bin/es-start.sh
  eservice/bin/es-stop.sh
  eservice/bin/ss-start.sh
  eservice/bin/ss-stop.sh
  eservice/pdo/eservice/scripts/EServiceCLI.py
  eservice/pdo/sservice/scripts/SServiceCLI.py
  pservice/Makefile
  pservice/bin/ps-start.sh
  pservice/bin/ps-stop.sh
  pservice/pdo/pservice/scripts/PServiceCLI.py
Labels: enhancement

#221 simplifying API for the commit module
  client/pdo/client/controller/commands/create.py
  client/pdo/client/controller/commands/send.py
  client/pdo/client/scripts/CreateCLI.py
  client/pdo/client/scripts/UpdateCLI.py
  python/pdo/contract/response.py
  python/pdo/contract/transaction.py
  python/pdo/service_client/storage.py
  python/pdo/test/contract.py
  python/pdo/test/request.py
Labels: bug

#223 simplified naming for sgx keys folders
  build/common-config.sh
  build/keys/sgx_mode_hw/.gitignore
  build/keys/sgx_mode_sim/.gitignore
  build/keys/sgx_mode_sim/sgx_ias_key.pem
  build/keys/sgx_mode_sim/sgx_spid.txt
  build/keys/sgx_mode_sim/sgx_spid_api_key.txt
  docker/Dockerfile.pdo-build
  docs/environment.md
  docs/install.md
Labels: documentation, enhancement
