Repository hyperledger-labs/private-data-objects, pull requests merged in 2019-05, with the labels that each got.

#189 Use the tinyscheme source to build the gipsy development interpreter.
  LICENSE
  build/__tools__/clean.sh
  build/__tools__/verify.sh
  common/interpreter/gipsy_scheme/packages/build-init-package.sh
  common/interpreter/gipsy_scheme/packages/init-package.scm
  contracts/auction/Makefile
  contracts/bin/gipsyscheme
  contracts/exchange/Makefile
  contracts/integer-key/Makefile
  contracts/packages/debug.scm
  contracts/packages/init.scm
  contracts/test-contracts/Makefile
  docker/Dockerfile.pdo-dev
Labels: enhancement

#191 Fix improper key reference in the build Makefile.
  build/Makefile
Labels: bug

#187 Provide all the key information in the provisioning service info command
  eservice/pdo/eservice/scripts/EServiceCLI.py
  pservice/pdo/pservice/scripts/PServiceCLI.py
Labels: enhancement

#192 Fix #173 ensuring that there is one secret from each provisioning service
  eservice/lib/libpdo_enclave/contract_secrets.cpp
  eservice/tests/test-secrets.py
Labels: bug

#198 Clean up after the pdo-shell tests
  build/__tools__/run-tests.sh
Labels: test

#197 Support new IAS authentication mode
  build/__tools__/expand-config
  build/__tools__/verify.sh
  build/common-config.sh
  build/keys/sgx_simulation/sgx_spid_api_key.txt
  build/keys/sgx_simulation/sgx_spid_key_cert.pem
  build/opt/pdo/etc/template/enclave.toml
  docker/Dockerfile.pdo-build
  docker/Makefile
  docker/README.md
  docker/sawtooth-pdo.sgx.yaml
  eservice/docs/REQUIREMENTS.md
  eservice/docs/test-scripts.md
  eservice/etc/sample_eservice.toml
  eservice/pdo/eservice/pdo_enclave.py
  eservice/pdo/eservice/utility/ias_client.py
  pservice/pdo/pservice/pdo_enclave.py
  pservice/pdo/pservice/utility/ias_client.py
Labels: enhancement

#200 Break out the build for keys and configuration files
  build/Makefile
Labels: enhancement

#206 remove dynamic allocation in contract state
  common/interpreter/ContractInterpreter.h
  common/interpreter/gipsy_scheme/GipsyInterpreter.cpp
  common/interpreter/gipsy_scheme/GipsyInterpreter.h
  common/state/basic_kv.h
  common/state/interpreter_kv.cpp
  common/state/interpreter_kv.h
  common/state/state_kv.cpp
  common/state/state_kv.h
  eservice/lib/libpdo_enclave/contract_code.cpp
  eservice/lib/libpdo_enclave/contract_enclave.cpp
  eservice/lib/libpdo_enclave/contract_request.cpp
  eservice/lib/libpdo_enclave/contract_request.h
  eservice/lib/libpdo_enclave/contract_response.cpp
  eservice/lib/libpdo_enclave/contract_response.h
  eservice/lib/libpdo_enclave/contract_state.cpp
  eservice/lib/libpdo_enclave/contract_state.h
Labels: bug, enhancement

#207 Update root documentation for new build and installation processes.
  BUILD.md
  PREREQUISITES.md
  README.md
  USAGE.md
  build/common-config.sh
  docs/docker_install.md
  docs/environment.md
  docs/host_install.md
  docs/install.md
  docs/specification.md
  docs/usage.md
  eservice/docs/REQUIREMENTS.md
Labels: documentation

#214 Stricter pre-build-verify test
  build/__tools__/verify-pre-build.sh
Labels: enhancement
